# How to Preprocess Data in Python

In [1]:
# https://builtin.com/machine-learning/how-to-preprocess-data-python
import pandas as pd

# 1. Load Data in Pandas

In [2]:
df = pd.read_csv("train.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [3]:
# there are 891 total rows but Age shows only 714(missing some data (NaN values)),...

# 2. Drop Columns That Aren’t Useful

In [4]:
# drop some of the columns which won't contribute much to our machine learning model
cols = ['Name', 'Ticket', 'Cabin']
df = df.drop(cols, axis=1)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Sex          891 non-null    object 
 4   Age          714 non-null    float64
 5   SibSp        891 non-null    int64  
 6   Parch        891 non-null    int64  
 7   Fare         891 non-null    float64
 8   Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(2)
memory usage: 62.8+ KB


# 3. Process Data Missing

## 3.1 Drop Rows With Missing Values

In [6]:
# Next we can drop all rows in the data that have missing values (NaNs)
df = df.dropna()
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 712 entries, 0 to 890
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  712 non-null    int64  
 1   Survived     712 non-null    int64  
 2   Pclass       712 non-null    int64  
 3   Sex          712 non-null    object 
 4   Age          712 non-null    float64
 5   SibSp        712 non-null    int64  
 6   Parch        712 non-null    int64  
 7   Fare         712 non-null    float64
 8   Embarked     712 non-null    object 
dtypes: float64(2), int64(5), object(2)
memory usage: 55.6+ KB


#### You can see line is same 712

In [7]:
df.head(10)

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare  \
0             1         0       3    male  22.0      1      0   7.2500   
1             2         1       1  female  38.0      1      0  71.2833   
2             3         1       3  female  26.0      0      0   7.9250   
3             4         1       1  female  35.0      1      0  53.1000   
4             5         0       3    male  35.0      0      0   8.0500   
6             7         0       1    male  54.0      0      0  51.8625   
7             8         0       3    male   2.0      3      1  21.0750   
8             9         1       3  female  27.0      0      2  11.1333   
9            10         1       2  female  14.0      1      0  30.0708   
10           11         1       3  female   4.0      1      1  16.7000   

   Embarked  
0         S  
1         C  
2         S  
3         S  
4         S  
6         S  
7         S  
8         S  
9         C  
10        S

#### THE PROBLEM WITH DROPPING ROWS

Sau khi loại bỏ các hàng có giá trị bị thiếu, chúng tôi nhận thấy tập dữ liệu giảm từ 891 xuống còn 712 hàng, điều đó có nghĩa là chúng tôi đang lãng phí dữ liệu. 
Các mô hình học máy cần dữ liệu để đào tạo và hoạt động tốt. 
Vì vậy, hãy bảo toàn dữ liệu và tận dụng nó nhiều nhất có thể.
Thêm về điều này dưới đây.

## 3.2 Creating Dummy Variables

In [8]:
# Instead of wasting our data, let’s convert the Pclass, Sex and Embarked to columns in Pandas and drop them after conversion.
df = pd.read_csv("train.csv")
dummies = []
cols = ['Pclass', 'Sex', 'Embarked']
for col in cols:
   dummies.append(pd.get_dummies(df[col]))
titanic_dummies = pd.concat(dummies, axis=1)
titanic_dummies.head(10)

1  2  3  female  male  C  Q  S
0  0  0  1       0     1  0  0  1
1  1  0  0       1     0  1  0  0
2  0  0  1       1     0  0  0  1
3  1  0  0       1     0  0  0  1
4  0  0  1       0     1  0  0  1
5  0  0  1       0     1  0  1  0
6  1  0  0       0     1  0  0  1
7  0  0  1       0     1  0  0  1
8  0  0  1       1     0  0  0  1
9  0  1  0       1     0  1  0  0

In [9]:
titanic_dummies.sort_values(['C','Q','S'], ascending=[1,1,1]).head(10)

1  2  3  female  male  C  Q  S
61   1  0  0       1     0  0  0  0
829  1  0  0       1     0  0  0  0
0    0  0  1       0     1  0  0  1
2    0  0  1       1     0  0  0  1
3    1  0  0       1     0  0  0  1
4    0  0  1       0     1  0  0  1
6    1  0  0       0     1  0  0  1
7    0  0  1       0     1  0  0  1
8    0  0  1       1     0  0  0  1
10   0  0  1       1     0  0  0  1

you can see line 61 have C = Q = S = 0, so this line is NaN (but with current this will contain all zero values

In [10]:
# concat data
df = pd.concat((df,titanic_dummies), axis=1)
df.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  1  2  3  female  male  C  \
0      0         A/5 21171   7.2500   NaN        S  0  0  1       0     1  0   
1      0          PC 17599  71.2833   C85        C  1  0  0       1     0  1   
2      0  STON/O2. 3101282   7.9250   NaN        S  0  0  1       1     0  0   
3      0            113803  53.1000  C123        S  1  0  0       1     0  0   
4      0            373450   8.0500   NaN        S  0  0  1       0     1  0   
5      0            330877   8.4583   NaN        Q  0  0  1       0     1  0   
6      0             17463  51.8625   E46        S  1  0  0       0     1  0   
7      1            349909  21.0750   NaN        S  0  0  1       0     1  0   
8      2            347742  11.1333   NaN        S  0  0  1       1     0  0   
9      0            237736  30.0708   NaN        C  0  1  0       1     0  1   

   Q  S  
0  0  1  
1  0  0  
2  0  1  
3  0  1  
4  0  1  
5  1  0  
6  0  1  
7  0  1  
8  0  1  
9  0  0

In [11]:
# Now that we converted Pclass, Sexand Embarked values into columns, we drop the redundant columns from the data frame.
df = df.drop(['Pclass', 'Sex', 'Embarked'], axis=1)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Name         891 non-null    object 
 3   Age          714 non-null    float64
 4   SibSp        891 non-null    int64  
 5   Parch        891 non-null    int64  
 6   Ticket       891 non-null    object 
 7   Fare         891 non-null    float64
 8   Cabin        204 non-null    object 
 9   1            891 non-null    uint8  
 10  2            891 non-null    uint8  
 11  3            891 non-null    uint8  
 12  female       891 non-null    uint8  
 13  male         891 non-null    uint8  
 14  C            891 non-null    uint8  
 15  Q            891 non-null    uint8  
 16  S            891 non-null    uint8  
dtypes: float64(2), int64(4), object(3), uint8(8)
memory usage: 69.7+ KB


#### You can see Age missing data (714 < 891)

In [12]:
# drop some of the columns which won't contribute much to our machine learning model
cols = ['Name', 'Ticket', 'Cabin']
df = df.drop(cols, axis=1)

# 4. Take Care of Missing Data

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Age          714 non-null    float64
 3   SibSp        891 non-null    int64  
 4   Parch        891 non-null    int64  
 5   Fare         891 non-null    float64
 6   1            891 non-null    uint8  
 7   2            891 non-null    uint8  
 8   3            891 non-null    uint8  
 9   female       891 non-null    uint8  
 10  male         891 non-null    uint8  
 11  C            891 non-null    uint8  
 12  Q            891 non-null    uint8  
 13  S            891 non-null    uint8  
dtypes: float64(2), int64(4), uint8(8)
memory usage: 48.9 KB


In [14]:
# Everything’s clean now, except Age, which has lots of missing values. 
# Let’s compute a median or interpolate() all the ages and fill those missing age values.
# Pandas has an interpolate() function that will replace all the missing NaNs to interpolated values.
df['Age'] = df['Age'].interpolate()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Age          891 non-null    float64
 3   SibSp        891 non-null    int64  
 4   Parch        891 non-null    int64  
 5   Fare         891 non-null    float64
 6   1            891 non-null    uint8  
 7   2            891 non-null    uint8  
 8   3            891 non-null    uint8  
 9   female       891 non-null    uint8  
 10  male         891 non-null    uint8  
 11  C            891 non-null    uint8  
 12  Q            891 non-null    uint8  
 13  S            891 non-null    uint8  
dtypes: float64(2), int64(4), uint8(8)
memory usage: 48.9 KB


# 5. Save data Preprocess

In [15]:
# Survived is result
df.head(10)

PassengerId  Survived   Age  SibSp  Parch     Fare  1  2  3  female  male  \
0            1         0  22.0      1      0   7.2500  0  0  1       0     1   
1            2         1  38.0      1      0  71.2833  1  0  0       1     0   
2            3         1  26.0      0      0   7.9250  0  0  1       1     0   
3            4         1  35.0      1      0  53.1000  1  0  0       1     0   
4            5         0  35.0      0      0   8.0500  0  0  1       0     1   
5            6         0  44.5      0      0   8.4583  0  0  1       0     1   
6            7         0  54.0      0      0  51.8625  1  0  0       0     1   
7            8         0   2.0      3      1  21.0750  0  0  1       0     1   
8            9         1  27.0      0      2  11.1333  0  0  1       1     0   
9           10         1  14.0      1      0  30.0708  0  1  0       1     0   

   C  Q  S  
0  0  0  1  
1  1  0  0  
2  0  0  1  
3  0  0  1  
4  0  0  1  
5  0  1  0  
6  0  0  1  
7  0  0  1  
8  0  0  1  
9  1  0  0

In [18]:
df.to_csv("preprocess.csv", index=False)

# 6. Convert the Data Frame to NumPy

In [17]:
df.head(10)

PassengerId  Survived   Age  SibSp  Parch     Fare  1  2  3  female  male  \
0            1         0  22.0      1      0   7.2500  0  0  1       0     1   
1            2         1  38.0      1      0  71.2833  1  0  0       1     0   
2            3         1  26.0      0      0   7.9250  0  0  1       1     0   
3            4         1  35.0      1      0  53.1000  1  0  0       1     0   
4            5         0  35.0      0      0   8.0500  0  0  1       0     1   
5            6         0  44.5      0      0   8.4583  0  0  1       0     1   
6            7         0  54.0      0      0  51.8625  1  0  0       0     1   
7            8         0   2.0      3      1  21.0750  0  0  1       0     1   
8            9         1  27.0      0      2  11.1333  0  0  1       1     0   
9           10         1  14.0      1      0  30.0708  0  1  0       1     0   

   C  Q  S  
0  0  0  1  
1  1  0  0  
2  0  0  1  
3  0  0  1  
4  0  0  1  
5  0  1  0  
6  0  0  1  
7  0  0  1  
8  0  0  1  
9  1  0  0

In [19]:
# get all values of df not header
X = df.values
X[:100]

array([[  1.,   0.,  22., ...,   0.,   0.,   1.],
       [  2.,   1.,  38., ...,   1.,   0.,   0.],
       [  3.,   1.,  26., ...,   0.,   0.,   1.],
       ...,
       [ 98.,   1.,  23., ...,   1.,   0.,   0.],
       [ 99.,   1.,  34., ...,   0.,   0.,   1.],
       [100.,   0.,  34., ...,   0.,   0.,   1.]])

In [20]:
y = df['Survived'].values
y[:100]

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0], dtype=int64)

In [21]:
import numpy as np
# delete cols Survived
X = np.delete(X, 1, axis=1)
X

array([[  1. ,  22. ,   1. , ...,   0. ,   0. ,   1. ],
       [  2. ,  38. ,   1. , ...,   1. ,   0. ,   0. ],
       [  3. ,  26. ,   0. , ...,   0. ,   0. ,   1. ],
       ...,
       [889. ,  22.5,   1. , ...,   0. ,   0. ,   1. ],
       [890. ,  26. ,   0. , ...,   1. ,   0. ,   0. ],
       [891. ,  32. ,   0. , ...,   0. ,   1. ,   0. ]])

# 7. Divide the Data Set Into Training Data and Test Data

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [23]:
print(len(X_train))
print(len(X_test))

623
268
